/*
 * test-api dev
 *
 * test api 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetAuthers - Your GET endpoint
func GetAuthers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAuthersId - Your GET endpoint
func GetAuthersId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetBooks - Your GET endpoint
func GetBooks(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetBooksId - Your GET endpoint
func GetBooksId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetCategories - Your GET endpoint
func GetCategories(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetCategoriesId - Your GET endpoint
func GetCategoriesId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostAuthers - 
func PostAuthers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostBooks - 
func PostBooks(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
