/*
 * test-api dev
 *
 * test api 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteAuthersId - 
func DeleteAuthersId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteBooksId - 
func DeleteBooksId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteCategoriesId - 
func DeleteCategoriesId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetBooksId - Your GET endpoint
func GetBooksId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PatchAuthersId - 
func PatchAuthersId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PatchBooksId - 
func PatchBooksId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PatchCategoriesId - 
func PatchCategoriesId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostAuthers - 
func PostAuthers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostBooks - 
func PostBooks(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostCategories - 
func PostCategories(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
