/*
 * test-api dev
 *
 * test api 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Book struct {

	Id int32 `json:"id,omitempty"`

	AutherId int32 `json:"auther_id,omitempty"`

	CategoryList []int32 `json:"category_list,omitempty"`
}
