/*
 * test-api dev
 *
 * test api 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Category struct for Category
type Category struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
