/*
 * test-api dev
 *
 * test api 
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// AdminApiRouter defines the required methods for binding the api requests to a responses for the AdminApi
// The AdminApiRouter implementation should parse necessary information from the http request, 
// pass the data to a AdminApiServicer to perform the required actions, then write the service results to the http response.
type AdminApiRouter interface { 
	DeleteAuthersId(http.ResponseWriter, *http.Request)
	DeleteBooksId(http.ResponseWriter, *http.Request)
	DeleteCategoriesId(http.ResponseWriter, *http.Request)
	GetBooksId(http.ResponseWriter, *http.Request)
	PatchAuthersId(http.ResponseWriter, *http.Request)
	PatchBooksId(http.ResponseWriter, *http.Request)
	PatchCategoriesId(http.ResponseWriter, *http.Request)
	PostAuthers(http.ResponseWriter, *http.Request)
	PostBooks(http.ResponseWriter, *http.Request)
	PostCategories(http.ResponseWriter, *http.Request)
}
// AllApiRouter defines the required methods for binding the api requests to a responses for the AllApi
// The AllApiRouter implementation should parse necessary information from the http request, 
// pass the data to a AllApiServicer to perform the required actions, then write the service results to the http response.
type AllApiRouter interface { 
	GetAuthers(http.ResponseWriter, *http.Request)
	GetAuthersId(http.ResponseWriter, *http.Request)
	GetBooks(http.ResponseWriter, *http.Request)
	GetBooksId(http.ResponseWriter, *http.Request)
	GetCategories(http.ResponseWriter, *http.Request)
	GetCategoriesId(http.ResponseWriter, *http.Request)
	PostAuthers(http.ResponseWriter, *http.Request)
	PostBooks(http.ResponseWriter, *http.Request)
}


// AdminApiServicer defines the api actions for the AdminApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type AdminApiServicer interface { 
	DeleteAuthersId(string) (interface{}, error)
	DeleteBooksId(string) (interface{}, error)
	DeleteCategoriesId(string) (interface{}, error)
	GetBooksId(string) (interface{}, error)
	PatchAuthersId(string, Auther) (interface{}, error)
	PatchBooksId(string, Book) (interface{}, error)
	PatchCategoriesId(string, Category) (interface{}, error)
	PostAuthers(Auther) (interface{}, error)
	PostBooks(Book) (interface{}, error)
	PostCategories(Category) (interface{}, error)
}


// AllApiServicer defines the api actions for the AllApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type AllApiServicer interface { 
	GetAuthers() (interface{}, error)
	GetAuthersId(string) (interface{}, error)
	GetBooks() (interface{}, error)
	GetBooksId(string) (interface{}, error)
	GetCategories() (interface{}, error)
	GetCategoriesId(string) (interface{}, error)
	PostAuthers(Auther) (interface{}, error)
	PostBooks(Book) (interface{}, error)
}
